### ISSUE TITLE
NPM install fails at pngquant-bin

### ISSUE THREAD

**Issue by fabm3n** [SolderIO/solder#128]
At the npm install part, the installation crashes
```
> pngquant-bin@4.0.0 postinstall /var/www/solder/node_modules/pngquant-bin
> node lib/install.js

  ⚠ The `/var/www/solder/node_modules/pngquant-bin/vendor/pngquant` binary doesn't seem to work correctly
  ⚠ pngquant pre-build test failed
  ℹ compiling from source
  ✔ pngquant pre-build test passed successfully
  ✖ Error: pngquant failed to build, make sure that libpng-dev is installed
    at Promise.all.then.arr (/var/www/solder/node_modules/pngquant-bin/node_modules/bin-build/node_modules/execa/index.js:231:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pngquant-bin@4.0.0 postinstall: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pngquant-bin@4.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-06T14_41_44_149Z-debug.log
```
NPM Version: 6.1.0
NodeJS Version: 8.11.3
Server running Ubuntu 18.04
libpng-dev Version: 1.6.34-1

**Comment by fabm3n** [comment]
After installing gcc it works perfectly. Could you add gcc to the Prerequisites?
